DROP INDEX IF EXISTS idx_magnets_coords;

WITH words_array AS (
  SELECT array[
    --  Standard kit
  '&','&','a','a','a','a','a','a','about','above','ache','ad','after','all','am','am','an','an','and','and','and','and','apparatus','are','are','arm','as','as','as','as','ask','at','at','at','away','bare','be','beat','beauty','bed','beneath','bitter','black','blood','blow','blue','boil','boy','breast','but','but','but','but','butt','by','by','can','chant','chocolate','cool','could','crush','cry','d','day','death','delirious','diamond','did','do','do','dream','dress','drive','drool','drunk','eat','ed','ed','ed','ed','egg','elaborate','enormous','er','es','est','fast','feet','fiddle','finger','fluff','for','forest','frantic','friend','from','from','garden','girl','go','goddess','gorgeous','gown','hair','has','have','have','he','he','head','heave','her','her','here','him','his','his','honey','hot','how','I','I','I','I','if','in','in','in','ing','ing','ing','ing','ing','ing','is','is','is','is','is','it','it','it','juice','lake','language','languid','lather','lazy','less','let','lick','lie','life','light','like','like','like','live','love','luscious','lust','ly','ly','ly','ly','mad','man','me','me','me','mean','meat','men','milk','mist','moan','moon','mother','music','must','my','my','my','need','never','no','no','not','not','of','of','of','of','on','on','one','or','our','over','pant','peach','petal','picture','pink','play','please','pole','pound','puppy','purple','put','r','r','rain','raw','recall','red','repulsive','rip','rock','rose','run','rust','s','s','s','s','s','s','s','s','s','s','s','sad','said','sausage','say','scream','sea','see','shadow','she','she','shine','ship','shot','show','sing','sit','skin','sky','sleep','smear','smell','smooth','so','soar','some','sordid','spray','spring','still','stop','storm','suit','summer','sun','sweat','sweet','swim','symphony','the','the','the','the','the','their','there','these','they','those','though','thousand','through','time','tiny','to','to','to','together','tongue','trudge','TV','ugly','up','urge','us','use','want','want','was','watch','water','wax','we','we','were','what','when','whisper','who','why','will','wind','with','with','woman','worship','y','y','y','y','yet','you','you','you','you',

  -- Standard kit again
  '&','&','a','a','a','a','a','a','about','above','ache','ad','after','all','am','am','an','an','and','and','and','and','apparatus','are','are','arm','as','as','as','as','ask','at','at','at','away','bare','be','beat','beauty','bed','beneath','bitter','black','blood','blow','blue','boil','boy','breast','but','but','but','but','butt','by','by','can','chant','chocolate','cool','could','crush','cry','d','day','death','delirious','diamond','did','do','do','dream','dress','drive','drool','drunk','eat','ed','ed','ed','ed','egg','elaborate','enormous','er','es','est','fast','feet','fiddle','finger','fluff','for','forest','frantic','friend','from','from','garden','girl','go','goddess','gorgeous','gown','hair','has','have','have','he','he','head','heave','her','her','here','him','his','his','honey','hot','how','I','I','I','I','if','in','in','in','ing','ing','ing','ing','ing','ing','is','is','is','is','is','it','it','it','juice','lake','language','languid','lather','lazy','less','let','lick','lie','life','light','like','like','like','live','love','luscious','lust','ly','ly','ly','ly','mad','man','me','me','me','mean','meat','men','milk','mist','moan','moon','mother','music','must','my','my','my','need','never','no','no','not','not','of','of','of','of','on','on','one','or','our','over','pant','peach','petal','picture','pink','play','please','pole','pound','puppy','purple','put','r','r','rain','raw','recall','red','repulsive','rip','rock','rose','run','rust','s','s','s','s','s','s','s','s','s','s','s','sad','said','sausage','say','scream','sea','see','shadow','she','she','shine','ship','shot','show','sing','sit','skin','sky','sleep','smear','smell','smooth','so','soar','some','sordid','spray','spring','still','stop','storm','suit','summer','sun','sweat','sweet','swim','symphony','the','the','the','the','the','their','there','these','they','those','though','thousand','through','time','tiny','to','to','to','together','tongue','trudge','TV','ugly','up','urge','us','use','want','want','was','watch','water','wax','we','we','were','what','when','whisper','who','why','will','wind','with','with','woman','worship','y','y','y','y','yet','you','you','you','you',

  -- Poet kit
  '&','&','&','&','a','a','a','a','a','a','a','about','after','air','all','almost','always','am','an','an','and','and','and','and','angel','are','are','as','as','ask','at','at','away','baby','be','belly','bleed','blue','blush','born','boy','breath','breeze','brilliant','bring','broken','brother','bug','but','but','but','by','cake','can','candy','caramel','cat','celebrate','champagne','child','cloud','coffee','color','come','concrete','cool','corduroy','could','crap','cup','d','d','dance','dark','day','dazzle','decay','delicious','desire','devour','did','die','dirt','do','do','dog','drink','e','e','eat','ed','ed','ed','embrace','er','er','es','es','eternity','explore','eye','fat','father','ferocious','fever','fire','fish','flower','fly','fool','for','for','for','from','from','ghost','girl','give','glass','go','go','god','good','grass','green','growl','hard','has','haunt','have','he','he','heal','heart','her','her','here','him','his','hole','home','hot','how','I','I','I','I','I','ice','if','in','in','in','ing','ing','ing','ing','ing','ing','is','is','is','is','is','it','it','it','it','joy','kiss','laugh','less','let','lie','life','like','like','like','linger','lip','liquid','listen','live','long','look','ly','ly','magic','make','man','marble','may','me','me','melt','men','moist','more','morning','must','my','my','naked','need','never','night','no','no','not','not','o','ocean','of','of','of','of','old','on','on','one','only','open','or','our','out','over','peace','perfume','picture','pie','poetry','poison','porcelain','prisoner','put','r','r','red','remember','rhythm','s','s','s','s','s','s','s','s','sacred','sad','said','sail','salt','secret','see','self','sex','she','she','sister','sky','slow','smile','smoke','so','soft','some','son','star','steam','steel','surround','than','that','the','the','the','the','their','them','then','there','they','thing','this','this','those','though','throb','time','to','to','to','to','tree','two','universe','up','use','vast','velvet','voice','wake','warm','was','we','we','were','wet','when','which','who','wild','will','window','with','with','woman','women','word','work','would','y','y','y','yet','you','you','you','young',

  -- Poet kit again
  '&','&','&','&','a','a','a','a','a','a','a','about','after','air','all','almost','always','am','an','an','and','and','and','and','angel','are','are','as','as','ask','at','at','away','baby','be','belly','bleed','blue','blush','born','boy','breath','breeze','brilliant','bring','broken','brother','bug','but','but','but','by','cake','can','candy','caramel','cat','celebrate','champagne','child','cloud','coffee','color','come','concrete','cool','corduroy','could','crap','cup','d','d','dance','dark','day','dazzle','decay','delicious','desire','devour','did','die','dirt','do','do','dog','drink','e','e','eat','ed','ed','ed','embrace','er','er','es','es','eternity','explore','eye','fat','father','ferocious','fever','fire','fish','flower','fly','fool','for','for','for','from','from','ghost','girl','give','glass','go','go','god','good','grass','green','growl','hard','has','haunt','have','he','he','heal','heart','her','her','here','him','his','hole','home','hot','how','I','I','I','I','I','ice','if','in','in','in','ing','ing','ing','ing','ing','ing','is','is','is','is','is','it','it','it','it','joy','kiss','laugh','less','let','lie','life','like','like','like','linger','lip','liquid','listen','live','long','look','ly','ly','magic','make','man','marble','may','me','me','melt','men','moist','more','morning','must','my','my','naked','need','never','night','no','no','not','not','o','ocean','of','of','of','of','old','on','on','one','only','open','or','our','out','over','peace','perfume','picture','pie','poetry','poison','porcelain','prisoner','put','r','r','red','remember','rhythm','s','s','s','s','s','s','s','s','sacred','sad','said','sail','salt','secret','see','self','sex','she','she','sister','sky','slow','smile','smoke','so','soft','some','son','star','steam','steel','surround','than','that','the','the','the','the','their','them','then','there','they','thing','this','this','those','though','throb','time','to','to','to','to','tree','two','universe','up','use','vast','velvet','voice','wake','warm','was','we','we','were','wet','when','which','who','wild','will','window','with','with','woman','women','word','work','would','y','y','y','yet','you','you','you','young',

  -- Cat kit
  '&','a','a','able','about','above','across','affection','after','all','almost','always','am','an','and','and','are','as','at','at','ate','be','beautiful','best','bird','black','box','break','brown','but','by','calico','can','care','cat','cat','catch','chase','clean','climb','come','companion','could','crazy','cunning','curious','d','day','did','dish','do','dream','drink','ed','ed','er','es','est','every','explore','face','feed','feel','feet','feline','food','for','friend','frisky','from','full','fur','gift','give','gray','has','have','he','hear','her','here','him','his','hiss','home','how','hunt','I','I','if','in','ing','ing','is','is','it','kiss','kitty','know','lap','leap','lick','lie','life','light','like','litter','little','live','long','love','ly','make','me','meow','mice','milk','mischievous','mouse','must','my','my','never','night','no','not','of','of','old','on','only','or','our','out','paw','perfect','pet','place','play','post','pounce','purr','pussy','quiet','r','s','s','s','safe','say','scratch','see','she','siamese','sleek','sleep','slink','snooze','so','sofa','soft','soon','special','stalk','string','sun','swat','sweet','tabby','tail','that','the','the','then','there','they','thing','think','this','though','tiger','to','too','toy','trick','up','us','use','warm','was','watch','water','we','were','when','whisker','white','why','wild','with','wonderful','would','y','y','yard','you','you',

  -- Haiku kit
  '&','a','a','about','above','always','am','an','and','and','are','as','at','autumn','bark','be','before','beneath','between','birch','black','bloom','blossom','blue','breath','but','by','can','cat','child','cicada','cloud','cold','come','concrete','crab','creak','cry','d','dandelion','dawn','dead','did','do','do','dog','dream','drop','e','early','eat','ed','est','evening','every','eye','face','fall','field','fish','flower','fly','for','freeze','friend','from','garden','give','grass','green','happy','hard','harvest','has','have','he','her','here','him','his','hot','house','how','howl','I','I','ice','if','in','ing','ing','insect','investigate','is','is','it','journey','laugh','leaf','leave','life','light','like','like','listen','live','ly','ly','make','man','me','melt','moon','morning','mouth','mushroom','must','my','my','night','no','of','of','off','on','or','our','out','owl','people','petal','plant','purple','r','rain','refrigerator','rise','road','roof','rust','s','s','sad','say','see','she','shell','shiver','shore','side','skin','sleep','small','smile','snow','so','some','song','soon','sound','spring','stand','still','stream','summer','sun','tear','than','that','the','the','then','there','they','this','though','through','thunder','to','to','too','tree','trickle','up','very','walk','want','was','water','we','weed','were','wet','when','while','whisper','wild','will','wind','window','winter','with','woman','wood','y','y','yellow','you','you',

  -- Zen kit
  '&','a','a','about','accept','all','allow','always','am','an','and','are','as','at','aura','awake','bad','be','being','believe','between','bird','body','breath','breathe','buddha','but','by','calm','can','come','compassion','confusion','connect','control','d','deep','desire','dharma','did','disconnect','do','e','easy','ed','ego','empty','energy','enlighten','er','es','every','everything','eye','find','flow','for','from','ful','gain','garden','give','good','grow','hard','harmony','has','have','he','hear','her','here','him','his','how','human','I','I','idea','if','illusion','in','in','ing','ing','insight','intution','inward','is','is','it','judgment','karma','know','koan','large','learn','life','light','like','like','listen','live','look','love','ly','ly','make','mantra','material','me','meditate','mind','mindful','moon','more','must','my','my','nature','no','nothing','now','of','of','on','only','or','our','out','pain','peace','practice','present','r','reality','release','river','s','s','same','see','self','selfless','serenity','she','silence','simplicity','small','so','some','song','speak','spirit','storm','sun','sutra','temple','than','that','the','the','the','then','there','they','think','this','those','though','thought','through','to','today','too','tranquil','tree','trust','truth','try','turn','understand','universe','up','us','use','very','virtue','was','water','we','were','which','whisper','who','why','will','wind','wisdom','with','within','wor','world','would','y','you','zen','zen',

  -- Love kit
  'a','a','all','always','am','an','and','and','angel','are','are','as','as','at','at','away','be','be','believe','belong','beside','best','better','between','big','bloom','boy','bread','but','but','by','can','care','charm','cheer','chocolate','come','could','dance','day','dew','do','dream','each','ed','emotion','er','es','est','evening','ever','every','faith','fascinate','feel','felt','fill','find','flower','for','for','friend','fun','gentle','girl','give','god','goddess','good','grow','hand','happy','has','have','he','he','he','heart','help','her','here','hero','him','his','his','hold','hug','I','I','if','in','ing','ing','ing','is','is','it','join','joy','keep','kind','know','language','large','laugh','life','life','light','like','listen','live','look','love','love','luck','ly','ly','make','man','me','me','mind','moment','music','mutual','my','my','need','neighbor','never','night','of','off','on','one','only','or','our','over','peace','play','please','power','promise','receive','rhapsody','s','s','s','sacred','say','share','she','she','she','sky','smile','so','soft','soul','star','strong','sun','sweet','tell','thank','that','the','the','the','them','then','there','they','think','this','though','through','time','tiny','to','to','together','true','trust','two','under','universe','up','us','use','want','want','warm','was','we','we','were','when','where','which','wish','with','woman','y','you','you','your',

  -- Moon kit
  '&','a','a','about','all','always','am','an','and','are','as','at','baby','bad','be','beam','beautiful','behind','big','big','blood','blue','bright','bring','broken','but','by','can','cloud','cold','come','crescent','cross','d','dark','deep','did','do','down','e','earth','ed','enormous','er','er','es','every','eye','face','fever','fingernail','follow','for','for','friend','from','full','gibbous','give','gleam','goddess','harvest','has','have','he','heart','here','him','his','home','hope','how','howl','I','I','if','imagine','in','in','ing','ing','ing','is','is','it','jump','June','kill','know','light','like','like','live','long','look','love','love','lover','luna','lunar','ly','ly','make','me','moon','moon','more','morning','mourn','must','my','my','night','no','ocean','of','of','old','on','only','or','orbit','our','out','pale','perfect','pine','planet','poem','pull','r','rise','romance','romantic','s','s','sad','same','satellite','sea','secret','see','serene','set','shadow','she','shine','below','sick','silent','silver','sing','sky','slow','small','so','some','song','space','spirit','spoon','spring','star','summer','sweet','than','that','the','the','then','there','they','this','though','through','tide','to','too','tranquility','traverse','tree','true','try','under','up','upon','us','use','wane','was','watch','water','wax','we','weary','wedge','were','who','why','will','winter','wish','with','would','write','y','you','you',

  -- Pride kit
  '!','a','a','about','alone','always','am','an','and','are','as','at','attack','be','beautiful','being','believe','belong','better','bi','bit','bold','but','by','can','celebrate','celebration','cis','come','community','create','d','day','did','dignity','do','don’t','drag','drink','ed','emotional','er','er','es','event','every','everyone','express','fear','feel','for','forever','free','freedom','from','gay','give','LGBT','go','happy','has','have','he','heal','hear','help','her','here','hide','him','his','honor','hope','how','human','humanity','I','I','if','important','in','in','ing','ing','is','is','it','joy','judgment','know','lesbian','let','light','like','like','long','love','love','ly','ly','make','many','march','me','mean','month','more','must','my','my','myself','need','no','not','not','of','of','okay','on','once','one','only','or','our','out','out','pain','parade','party','peace','people','person','place','play','pride','proclaim','proud','queer','r','rainbow','real','relax','remember','right','rise','s','s','safe','safety','see','see','self','sense','shadow','shame','she','shine','shout','sing','so','some','song','soul','space','stand','straight','street','sun','take','than','that','the','the','them','there','they','thing','this','though','through','time','to','today','together','too','trans','try','under','up','us','use','want','was','we','we','wear','were','who','why','will','with','without','would','y','year','yes','you','you',

  -- Wabi-sabi kit
  'a','a','about','age','all','alone','always','am','an','and','appear','are','arrange','art','as','as','at','atmosphere','bare','be','beautiful','beauty','bloom','blossom','broken','but','by','calm','can','ceremony','charm','come','complete','contemplate','crack','d','dead','decay','delicate','delight','did','die','do','e','ed','ephemeral','equal','er','er','es','ever','every','fade','fall','feel','fill','fix','flaw','fleeting','flow','flower','for','forest','fracture','fresh','from','give','gold','grief','ground','grow','has','have','he','her','here','him','his','how','I','I','if','imperfect','in','in','ing','ing','is','is','ist','it','know','leaf','let','life','like','like','line','live','lone','love','lovely','ly','ly','make','me','melancholy','mend','ment','minimal','moment','more','much','must','my','my','nature','ness','no','of','of','old','on','one','only','or','our','out','pass','peace','pebble','perfect','permanent','petal','poem','pray','profound','r','rain','reflect','repair','ripple','ritual','root','ruin','rust','s','s','sacred','sad','see','serene','she','short','show','simple','simplicity','single','so','soft','some','span','spirit','spiritual','still','sweet','teapot','than','that','the','the','then','there','they','thing','this','though','through','time','tion','to','too','transient','try','twig','up','us','use','was','water','we','were','wet','where','who','why','will','wisdom','wise','with','wither','world','worn','y','you','your','zen'
  ]
AS arr
)
INSERT INTO magnets (coords, rotation, word, last_modifier)
SELECT
  Point(
    FLOOR(random() * 400001 - 200000)::INTEGER,
    FLOOR(random() * 400001 - 200000)::INTEGER
  ),
  -- Postgres 17 should allow for random(-5, 5) instead
  FLOOR(random() * 11 - 5)::INTEGER,
  arr[1 + (random() * (array_length(arr, 1) - 1))::INTEGER] AS word,
  NULL
FROM words_array
CROSS JOIN generate_series(1, 3000000);

CREATE INDEX IF NOT EXISTS idx_magnets_coords ON magnets USING gist (coords);
-- REINDEX INDEX CONCURRENTLY idx_magnets_coords;
CLUSTER magnets USING idx_magnets_coords;